# .github/workflows/build-deploy.yml
# taken from https://arc.codes/docs/en/guides/developer-experience/continuous-integration/github-actions#usage-example

name: Build and deploy

on: [ push, pull_request ]

jobs:
  # Build and test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build App
        uses: architect/action-build@v3
